<?php
	
	// no direct access
	defined('_STS_INCLUDE') or die('Restricted access');
			
	// Generated by exp_install.php Friday 18th of March 2022 01:33:10 PM
	// Stored in /var/www/domains/orcloud.exspeedite.net/htdocs/include/client1/exspeedite_config.php
	
	$sts_crm_timezone = "America/Chicago";
	$sts_crm_root = "https://client1.exspeedite.net";
	$sts_crm_dir = "/var/www/domains/orcloud.exspeedite.net/htdocs/";
	
	$sts_db_host	= "localhost";
	$sts_db_port	= "3306";
	$sts_username	= "exp_strawberry";
	$sts_password	= "S0rdf1sh!";
	$sts_database	= "1000";
	
	?>