<?php
	
	// no direct access
	defined('_STS_INCLUDE') or die('Restricted access');
			
	// Generated by exp_install.php Friday 28th of July 2023 09:30:39 AM
	// Stored in /var/www/domains/orcloud.exspeedite.net/htdocs/include/orcloud/exspeedite_config.php
	
	$sts_crm_timezone = "America/Chicago";
	$sts_crm_root = "https://orcloud.exspeedite.net";
	$sts_crm_dir = "/var/www/domains/orcloud.exspeedite.net/htdocs/";
	
	$sts_db_host	= "localhost";
	$sts_db_port	= "3306";
	$sts_username	= "exp_strawberry";
	$sts_password	= "S0rdf1sh!";
	$sts_database	= "f1";
	
	?>