<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.1 setup script
 * Date: Tue, 18 Jan 2022 02:13:58 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['only_db'] = '';
$cfg['Servers'][$i]['hide_db'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'F`V1.ji;}mJKmh\'ZS6{;iU_Q;=xA|N';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '/tmp/';
$cfg['SaveDir'] = '';
$cfg['TempDir'] = '/tmp/';
$cfg['ExecTimeLimit'] = 0;

?>