<?php
	
	// no direct access
	defined('_STS_INCLUDE') or die('Restricted access');
			
	// Generated by exp_install.php Thursday 17th of March 2022 01:04:40 PM
	$sts_crm_timezone = "America/Chicago";
	$sts_crm_root = "https://orcloud.exspeedite.net";
	$sts_crm_dir = "/var/www/domains/orcloud.exspeedite.net/htdocs/";
	
	$sts_db_host	= "localhost";
	$sts_db_port	= "3306";
	$sts_username	= "exp_strawberry";
	$sts_password	= "S0rdf1sh!";
	$sts_database	= "pipco1";
	
	?>